version: '3.8'

services:
  pocket-bank-frontend:
    container_name: pocket-bank-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4000/api
    command: yarn dev
